name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    container:
      image: abhishekf5/maven-abhishek-docker-agent:v1
      options: --user root

    env:
      SONAR_URL: http://44.211.80.125:9000/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Java
      run: |
        echo "JAVA_HOME = $JAVA_HOME"
        java -version
        javac -version

    - name: Build and Test
      run: |
        cd spring-boot-app
        mvn clean package -e -X

    - name: Check Java & Maven Version
      run: |
        java -version
        mvn -v

    - name: Static Code Analysis (SonarQube)
      env:
        SONAR_AUTH_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd /spring-boot-app
        mvn sonar:sonar \
          -Dsonar.login=$SONAR_AUTH_TOKEN \
          -Dsonar.host.url=${SONAR_URL}

    - name: Build Docker Image
      run: |
        cd spring-boot-app
        docker build -t vijay/ultimate-cicd:${{ github.run_number }} .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker push vijay/ultimate-cicd:${{ github.run_number }}

    - name: Update Deployment File
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_CUSTOM }}
      run: |
        git config user.email "vijay.r@gmail.com"
        git config user.name "Vijay R"

        sed -i "s/replaceImageTag/${{ github.run_number }}/g" \
        spring-boot-manifests/deployment.yml

        git add spring-boot-manifests/deployment.yml
        git commit -m "Update deployment image to version ${{ github.run_number }}"
        git push https://${GITHUB_TOKEN}@github.com/vijay-R820/GitHub-Actions-Zero-to-Hero HEAD:main
